/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ibxSoXtBGpQJ21i2zn1Jd7
// Component: _SROjryz8RTr
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { StrapiField } from "@plasmicpkgs/plasmic-strapi";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: ibxSoXtBGpQJ21i2zn1Jd7/projectcss
import sty from "./PlasmicTweetCard.module.css"; // plasmic-import: _SROjryz8RTr/css

createPlasmicElementProxy;

export const PlasmicTweetCard__VariantProps = new Array();

export const PlasmicTweetCard__ArgProps = new Array();

const $$ = {};

function PlasmicTweetCard__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root
      )}
    >
      <StrapiField
        className={classNames("__wab_instance", sty.strapiField__aodyD)}
        path={"t_title"}
      />

      <StrapiField
        className={classNames("__wab_instance", sty.strapiField__bCnB5)}
        path={"t_content"}
      />

      <StrapiField
        className={classNames("__wab_instance", sty.strapiField__m8Ngf)}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTweetCard__ArgProps,
          internalVariantPropNames: PlasmicTweetCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTweetCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTweetCard";
  } else {
    func.displayName = `PlasmicTweetCard.${nodeName}`;
  }
  return func;
}

export const PlasmicTweetCard = Object.assign(
  // Top-level PlasmicTweetCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicTweetCard
    internalVariantProps: PlasmicTweetCard__VariantProps,
    internalArgProps: PlasmicTweetCard__ArgProps
  }
);

export default PlasmicTweetCard;
/* prettier-ignore-end */
