/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ibxSoXtBGpQJ21i2zn1Jd7
import * as React from "react";
import { StrapiCredentialsProvider } from "@plasmicpkgs/plasmic-strapi";

export default function GlobalContextsProvider(props) {
  const { children, strapiCredentialsProviderProps } = props;
  return (
    <StrapiCredentialsProvider
      {...strapiCredentialsProviderProps}
      host={
        strapiCredentialsProviderProps &&
        "host" in strapiCredentialsProviderProps
          ? strapiCredentialsProviderProps.host
          : "https://strapi-production-99e8.up.railway.app/"
      }
      token={
        strapiCredentialsProviderProps &&
        "token" in strapiCredentialsProviderProps
          ? strapiCredentialsProviderProps.token
          : "8fea8f4ffa7a63d6228f6aec1c2a648bde581a1739b2df8dda19e31767801f8c87164b4f39ca1e2564d9ec42a562428f4ceab03b6d2f543b95f0bfc50a31bc3c237151dfb70de73a0916a88f29014a541091a3e05b8dfa919da8cfe2ffa86297bc6f32930558b6397f48e83e06772d582524c2bf1c8eba63140ec5def5b81890"
      }
    >
      {children}
    </StrapiCredentialsProvider>
  );
}
